---
title: "Scenario analysis for healthcare needs for COVID-19 in Georgia"
author: "Andreas Handel (ahandel@uga.edu), John M. Drake (jdrake@uga.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
header-includes:
  - \usepackage{amsmath}
output:
  pdf_document: default
  html_document:
    df_print: paged
bibliography: ["refs.bib"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE, warning=FALSE)
today <- Sys.Date()
# pull data directly from github repo
# data is generated by stochastic GA simulator
#state.data <- read.csv('https://raw.githubusercontent.com/CEIDatUGA/COVID-19-DATA/master/UScases_by_state_wikipedia.csv?token=ABQMQXYOBV7TFRDQXWX2YQC6PEFIU')
```


```{r styles}
source('style-definitions.R')
```

## Introduction

Modeling health care needs in GA for COVID-19.


## Assumptions

We assume that among those that are infected, X% require hospitalization.

Among those hospitalized, we assume X% require ventilators, X% require ICU.


```{r parameters-1}
#age structure of population
#https://www.census.gov/quickfacts/GA
Ntot = 10617423
Nc = 0.238*Ntot #under 18
Ne = 0.139*Ntot #>65 old
Na = Ntot - Nc - Ne #everyone between 18 and 65
```


```{r parameters-2}

```


